networks:
  mlops-network:
    external: true

services:
  mlflow:
    restart: always
    build: ./mlflow
    container_name: mlflow_2.14.1
    ports:
      - 5000:5000
    environment:
      - MLFLOW_S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    command: mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_ROOT} --host 0.0.0.0
    networks:
      mlops-network:
        ipv4_address: 172.61.0.5